apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: keycloak-gatekeeper
  files:
  - config.yml=conf/config_sample.yml
  - forbidden.html.tmpl=conf/forbidden.html.tmpl
  - sign_in.html.tmpl=conf/sign_in.html.tmpl

resources:
- keycloak-gatekeeper-deployment.yaml
- keycloak-gatekeeper-service.yaml
- keycloak-gatekeeper-route.yaml
